{{- if .Values.maillog.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: maillog-tls
rules:
- apiGroups:
  - ""
  resourceNames:
  - tls-secret-maillog
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
{{- end -}}
