{{- if .Values.maillog.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: maillog
  namespace: {{ .Release.Namespace }}
  labels:
    app: maillog
    chart: maillog
    release: maillog
    heritage: {{ .Release.Service }}
type: Opaque
data:
  config.yaml: {{ include "cronus/templates/maillog/_config.yaml.tpl" . | b64enc }}
{{- end -}}
