{{- if .Values.maillog.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: maillog
  annotations:
    {{- range $key, $value := .Values.maillog.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: {{ .Values.maillog.service.type }}
{{- if .Values.maillog.service.externalIPs }}
  externalIPs: {{ toYaml .Values.maillog.service.externalIPs | nindent 4 }}
{{- end }}
{{- if .Values.maillog.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.maillog.service.loadBalancerIP }}
{{- end }}
{{- if .Values.maillog.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.maillog.service.externalTrafficPolicy }}
{{- end }}
  ports:
    - name: http
      port: {{ .Values.maillog.server.http }}
      protocol: TCP
  selector:
    name: maillog
    instance: maillog
{{- end -}}
